version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ../app:/app:delegated
    ports:
      - '80:80'

  db:
    image: mysql:latest
    # Подключаем к общей сети с другими контейнерами
    networks:
      - default
    # Показываем наружу порт
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_DATABASE=order
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ../docker/volume_mysql:/var/lib/mysql
    container_name: app_mysql